name: Node.JS CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["CI/CD"]
    types:
      - completed  


jobs:
    # Unit Test job
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm install

      # - name: Run Unit Tests
      #   run: npm test

  validate-pr:
    name: Validate PR
    needs: [unit-test]
    runs-on: ubuntu-latest

    steps:
      - name: Check Unit Test Status
        id: test-status
        run: echo "::set-output name=status::$(if [ -s test-results.xml ]; then echo 'success'; else echo 'failure'; fi)"

      - name: Comment on PR
        if: steps.test-status.outputs.status == 'failure'
        run: |
          echo "Tests failed. This PR cannot be merged."
          exit 1

  build:
    name: User app
    runs-on: ubuntu-latest

    strategy: 
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout 
        uses: actions/checkout@v3 
        with: 
          fetch-depth: 0

      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v3 
        with: 
          node-version: ${{ matrix.node-version }}

      - name: NPM install,build
        run: |
          npm install
        # env: 
        #   MONGODB_URL: ${{ secrets.MONGODB_URL }}
        #   JWT_SECRET: ${{ secrets.JWT_SECRET }}
        #   MJ_API_KEY: ${{ secrets.MJ_API_KEY }}
        #   MJ_SECRET_KEY: ${{ secrets.MJ_SECRET_KEY }}
        #   FROM_EMAIL: ${{ secrets.FROM_EMAIL }}


  # Deploy job to fit render.com
  deploy:
    name: Deploy
    needs: [build] # Our tests must pass in order to run the deploy job
    runs-on: ubuntu-latest

    steps: 
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }} # Can be found as part of the Deploy Hook
          api-key: ${{ secrets.RENDER_API_KEY }} # Create your API key in Render Dashboard > Account Settings


  #Test job
  test:
    name: E2E tests
    needs: [deploy]
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Test Repository
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Run tests
        run: |
          npm install
          npm test      

# Workflow to trigger build and deploy after PR is merged
workflow "CI/CD" {
  resolves = ["build", "deploy","test"]
  on = "pull_request"
}

workflow_run:
  jobs: build, deploy, test
  types:
    - requested